### ISSUE TITLE
Add .gitignore to templates

### ISSUE THREAD

**Issue by wuelcas** [VoxaAI/voxa-cli#109]
Currently, we're generating a project (both javascript and typescript) without a `.gitignore`, causing a bad experience when initializing git on the project with the `node_modules` folder and other stuff. We need to add that file so it's generated by the `voxa-cli`

**Comment by papuruth** [comment]
Aren't they already added?

**Comment by n1rna** [comment]
hi, I would like to work on this, can you assign it to me?
