### ISSUE TITLE
Utterance samples of intents with yes/no change to true/false

### ISSUE THREAD

**Issue by patcat** [VoxaAI/voxa-cli#140]
It seems to be a part of a change to support Office 365, but in `/src/connectors/utils.ts` it looks like values of "yes" and "no" are changed to `true` and `false`?

When we have "yes" and "no" in our Google spreadsheet as responses to YesIntent and NoIntent, they get replaced when imported in... which isn't desired!

Any info on why this functionality has specifically been put in there? Am I missing something?

Thanks!

**Comment by patcat** [comment]
Also, having "false" as an utterance entry gets removed in the generated JSON too?

**Comment by rmberrios** [comment]
We do it for the download feature(DOWNLOAD_TAB), but it shouldn't change those utterances in the Intent. I'm going to address this. Since we use AMAZON.YesIntent and AMAZON.NoIntent we didn't have any problem.

**Comment by patcat** [comment]
Fantastic thanks — if you have a PR for the change when you've been able to address it and you need a hand testing it out, I can test it on our spreadsheet.
