### ISSUE TITLE
General skill information can't generate objects properly

### ISSUE THREAD

**Issue by matmunn** [VoxaAI/voxa-cli#65]
Using a sheet setup like this:
![image](https://user-images.githubusercontent.com/65853/57670824-52cce180-7654-11e9-9c68-92de9763ae19.png)

ends up generating  an agent configuration that looks like this:
```
  "defaultTimezone": "Australia/Melbourne",
  "webhook": [
    {
      "url": "https://example.org"
    },
    {
      "username": "foo"
    },
    {
      "password": "bar"
    },
    {
      "available": true
    },
    {
      "useForDomains": true
    },
    {
      "cloudFunctionsEnabled": false
    },
    {
      "cloudFunctionsInitialized": false
    }
  ],
```

Instead of assigning keys to a `webhook` object an array is created that has objects with a single property each.

Would you be interested in a PR to fix this behaviour?

**Comment by rmberrios** [comment]
@matmunn `dialogflow.webhook.url` is the correct path.

Where did you find that reference about an array? perhaps something is wrong in the documentation.

**Comment by matmunn** [comment]
There's nothing about it in the documentation at all. The implementation I found is in  `Processor.ts`, but I must have been understanding it wrong.

Maybe I'll look at improving the docs at some stage when I have some free time.
